name: Fast
favicon: null
layout_spectrum: 0.7181574434507638
typography_spectrum: 0.46703960350714624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6719789744820446
  lightness: 0.6854389482177794
  saturation: 0.3940949982497841
  rhythmicContrast: 0.6086519611999393
purpose: []
